# Generated by Django 5.2.9 on 2025-12-13 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transcription', 'verbose_name_plural': 'Transcriptions'},
        ),
        migrations.AlterModelOptions(
            name='transcriptionsettings',
            options={'verbose_name': 'Transcription Settings', 'verbose_name_plural': 'Transcription Settings'},
        ),
        migrations.RemoveIndex(
            model_name='transcription',
            name='transcripti_created_496420_idx',
        ),
        migrations.RemoveIndex(
            model_name='transcription',
            name='transcripti_user_id_34f042_idx',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='model_used',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='text',
        ),
        migrations.AddField(
            model_name='transcription',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When transcription was completed', null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Audio duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='error_message',
            field=models.TextField(blank=True, help_text="Error details if status is 'failed'"),
        ),
        migrations.AddField(
            model_name='transcription',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='model_name',
            field=models.CharField(default='whisper-large-v3', help_text='AI model used for transcription', max_length=50),
        ),
        migrations.AddField(
            model_name='transcription',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transcription',
            name='transcribed_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transcriptionsettings',
            name='auto_delete_audio',
            field=models.BooleanField(default=False, help_text='Automatically delete audio file after transcription'),
        ),
        migrations.AddField(
            model_name='transcriptionsettings',
            name='default_model',
            field=models.CharField(default='whisper-large-v3', help_text='Default AI model to use', max_length=50),
        ),
        migrations.AddField(
            model_name='transcriptionsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send email when transcription is complete'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='language',
            field=models.CharField(default='de', help_text="Language code (e.g., 'de', 'en')", max_length=10),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transcriptionsettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for transcription service (encrypted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='transcriptionsettings',
            name='backend_url',
            field=models.URLField(default='https://api.openai.com/v1/audio/transcriptions', help_text='Transcription service API endpoint'),
        ),
        migrations.AlterField(
            model_name='transcriptionsettings',
            name='default_language',
            field=models.CharField(default='de', help_text='Default language for transcriptions', max_length=10),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['user', 'status'], name='transcripti_user_id_e842ee_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['status', 'created_at'], name='transcripti_status_95a351_idx'),
        ),
    ]
