# Generated by Django 5.2.9 on 2026-02-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_alter_transcription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionsettings',
            name='backend_url',
            field=models.URLField(default='https://transcribe.simpliant-ds.eu', help_text='Base URL of the transcription service'),
        ),
    ]
